file = open("d:/teams.txt", "r")
print("First Line: ")
print(file.readline())
file.readline()
print("Third Line: ")
print(file.readline())
file.seek(0)
print("First line: ")
print(file.readline())
print("First character: ")
print(file.readline())
print(file.read(1))
file.close()

